#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

git_hooks_dir=$PLUSHU_ROOT/plugins/$PLUSHU_PLUGIN_NAME/git-hooks

# git-shell exclusively expects this kind of quoting for its argument.
# See https://git.kernel.org/cgit/git/git.git/tree/quote.c
# and https://git.kernel.org/cgit/git/git.git/tree/shell.c
sq_quote () {
  echo -n "'"
  echo -n $1 | sed 's/['\''!]/'\''\\\0'\''/g'
  echo "'"
}
sq_dequote () {
  echo $1 | xargs -x echo
}

case "$1" in
  git-*)
    cmd=$1
    repo=$2
    repo_path=$PLUSHU_ROOT/repos/$repo
    arg=`sq_quote "$repo_path"`

    # If we're receiving a pack for a repository that has
    # not yet been initialized
    if [[ $1 == "git-receive-pack" && ! -d "$repo_path/hooks" ]]; then

      # Initialize the repo
      git init --bare "$repo_path" > /dev/null

      # Link to this plugin's hooks
      rm -rf "$repo_path/hooks"
      ln -s "$git_hooks_dir" "$repo_path/hooks"
    fi

    # Forward to git-shell
    PLUSHU_REPO_NAME=$repo GIT_DIR=$repo_path git-shell -c "$cmd $arg"
    ;;
esac
