#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# swap stdout (pipe output) and fd3 (parent stdout)
exec 6>&1 >&3 3>&6 6>&-

if [[ -d "$1/.git" ]]; then
  cd "$1"

  old_rev=
  # If anything upstream is different from local
  if [[ -n `git fetch --dry-run 2>&1` ]]; then

    # Pull new revisions
    git fetch
    old_rev="$(git rev-parse HEAD)"
    new_rev="$(git rev-parse @{u})"
  fi

  # If there are changes to merge
  if [[ -n "$old_rev" && "$old_rev" != "$new_rev" ]]; then
    # merge them
    echo "Updating $2..."
    git merge @{u}

    printf "git %s %s\n" "$old_rev" "$new_rev" >&3
  else
    printf "git\n" >&3
  fi
fi
