#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# swap stdout (pipe output) and fd3 (parent stdout)
exec 6>&1 >&3 3>&6 6>&-

if [[ -d "$1/.git" ]]; then
  cd "$1"

  # If upstream is different from local
  if [[ -n `git status -zuno` ]]; then
    echo "Updating $2..."

    # Pull new revisions
    git fetch
    old_rev="$(git rev-parse HEAD)"
    new_rev="$(git rev-parse @{u})"

    # merge them
    git merge @{u}

    printf "git %s %s\n" "$old_rev" "$new_rev" >&3
  else
    printf "git\n" >&3
  fi
fi
